# Generated by Django 4.0.3 on 2022-04-03 20:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tilte', models.CharField(max_length=50)),
                ('subtitle', models.CharField(max_length=100)),
                ('image_page', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('author', models.CharField(max_length=100)),
                ('content', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('datetimecreation', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
