# Generated by Django 4.0.3 on 2022-04-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_tilte_page_title_alter_page_datetimecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='image_page',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
